name: "Build"
on:
  push:
  schedule:
  - cron: '30 22 * * 1'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        wine-branch:
        - stable
        - development
        - staging
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build -A ${{ matrix.wine-branch }}
    - name: Gather build metadata
      id: meta
      run: |
        echo "::set-output name=wine-version::$(cat result/wine_version)"
    - uses: actions/upload-artifact@v2
      with:
        name: wined3d-diablo-${{ steps.meta.outputs.wine-version }}
        path: result/dlls/wined3d.dll
